"""
path_constants.py
-----------------

프로젝트의 구조 통일, 산출물 생성/접근/저장 관리, 파이프라인 실행의 편의성 등을 위한
주요 디렉토리/파일/모듈 경로에 대한 상수 모음 모듈
(로컬 용)

해당 모듈에 선언된 경로 관련 상수들은 로컬용 프로젝트 구조를 전제로 작성된 부분으로,
배포 시엔 해당 모듈의 변수를 사용하지 않고 외부 환경변수 등의 경로 주입 방식 활용을 권고
"""


from config.constant.common.name_constants import (
    DATAS_DIRECTORY_NAME,
    SENTIMENT_MODEL_DIRECTORY_NAME,
    LOGS_DIRECTORY_NAME,
    CONFIG_DIRECTORY_NAME,
    SENTIMENT_LOGS_DIRECTORY_NAME,
    APP_LOG_FILE_NAME,
    SENTIMENT_EVENT_LOG_JSONL_FILE_NAME,
    SENTIMENT_CONFIG_TUNER_STATISTICS_META_LOG_JSONL_FILE_NAME,
    CONFIG_INI_FILE_NAME,
)
from config.constant.common.path_constants import (
    BASE_DIRECTORY_PATH,
)


# 로컬용 주요 (상위) 디렉토리 경로
LOCAL_DATAS_DIRECTORY_PATH = BASE_DIRECTORY_PATH / DATAS_DIRECTORY_NAME
LOCAL_SENTIMENT_MODEL_DIRECTORY_PATH = BASE_DIRECTORY_PATH / SENTIMENT_MODEL_DIRECTORY_NAME
LOCAL_LOGS_DIRECTORY_PATH = BASE_DIRECTORY_PATH / LOGS_DIRECTORY_NAME
LOCAL_CONFIG_DIRECTORY_PATH = BASE_DIRECTORY_PATH / CONFIG_DIRECTORY_NAME


# 로컬용 sentiment 추론 모델이 위치하는 디렉토리 경로
LOCAL_TRAINED_SENTIMENT_MODEL_DIRECTORY_PATH = (
        LOCAL_SENTIMENT_MODEL_DIRECTORY_PATH
        / 'roberta-finetuned'
        / 'content'
        / 'drive'
        / 'MyDrive'
        / 'roberta-finetuned'
)


# 로컬용 로그 관련 디렉토리 경로
LOCAL_APPLICATION_LOG_PATH = LOCAL_LOGS_DIRECTORY_PATH / APP_LOG_FILE_NAME

LOCAL_SENTIMENT_LOGS_DIRECTORY_PATH = LOCAL_LOGS_DIRECTORY_PATH / SENTIMENT_LOGS_DIRECTORY_NAME
LOCAL_SENTIMENT_EVENT_LOG_JSONL_PATH = LOCAL_SENTIMENT_LOGS_DIRECTORY_PATH / SENTIMENT_EVENT_LOG_JSONL_FILE_NAME
LOCAL_SENTIMENT_CONFIG_TUNER_STATISTICS_META_LOG_JSONL_PATH = (
        LOCAL_SENTIMENT_LOGS_DIRECTORY_PATH / SENTIMENT_CONFIG_TUNER_STATISTICS_META_LOG_JSONL_FILE_NAME
)


# 로컬용 외부 설정값 파일이 위치하는 디렉토리 경로
LOCAL_CONFIG_INI_PATH = LOCAL_CONFIG_DIRECTORY_PATH / CONFIG_INI_FILE_NAME
